// Typed API wrappers for the Action Center (Requirement 8).
//
// Actions are the "what needs to happen" side of business memory. They can be
// created manually by a human or generated by the AI from a *confirmed*
// knowledge item (Requirement 8.1/8.2); the `ai_generated` flag records which
// origin produced them so the UI can show a provenance indicator
// (Requirement 8.5). Every call is cookie-authenticated by the shared `api`
// client and scoped server-side to the caller's organization; filters are
// applied server-side in addition to that mandatory scoping (Requirement 8.3).
//
// Notable status codes surfaced as ApiError by the client:
//   - 409 when creating an action from an UNCONFIRMED knowledge item — an AI
//     action may only be generated from confirmed knowledge (Requirement 8.2).
//   - 404 on unknown / cross-tenant ids (Requirement 2.3).
//
// This module reuses the shared `ActionItem` / `ActionStatus` types from
// types.ts and only adds the request payload shapes.

import { api } from "./client";
import type { ActionItem, ActionStatus } from "./types";

/** Optional server-side filters for the action list (Requirement 8.3). */
export interface ActionFilters {
  status?: ActionStatus;
  businessEntityId?: string;
}

/** Request body of `POST /api/actions` (Requirement 8.1). */
export interface ActionCreate {
  title: string;
  description?: string;
  business_entity_id?: string;
  knowledge_item_id?: string;
  owner_id?: string;
  due_date?: string;
  evidence_text?: string;
}

/** Request body of `PATCH /api/actions/{id}` (Requirement 8.4). */
export interface ActionUpdate {
  title?: string;
  description?: string;
  business_entity_id?: string;
  owner_id?: string;
  due_date?: string;
  status?: ActionStatus;
  evidence_text?: string;
}

function buildActionQuery(filters: ActionFilters = {}): string {
  const params = new URLSearchParams();
  if (filters.status) params.set("status", filters.status);
  if (filters.businessEntityId)
    params.set("business_entity_id", filters.businessEntityId);
  const query = params.toString();
  return query ? `?${query}` : "";
}

export const actionsApi = {
  /**
   * List the organization's action items, newest first, optionally filtered by
   * status and/or connected business entity (Requirement 8.3).
   */
  list: (filters: ActionFilters = {}) =>
    api.get<ActionItem[]>(`/actions${buildActionQuery(filters)}`),

  /** Fetch one organization-scoped action for a direct detail route. */
  get: (actionId: string) => api.get<ActionItem>(`/actions/${actionId}`),

  /**
   * Create an action item (Requirement 8.1). A manual action is recorded with
   * `ai_generated=false`; supplying a confirmed `knowledge_item_id` yields an
   * AI-generated action, while an unconfirmed one is rejected with 409
   * (Requirement 8.2).
   */
  create: (payload: ActionCreate) =>
    api.post<ActionItem>("/actions", payload),

  /**
   * Update an action item, e.g. mark it done with `{ status: "DONE" }`
   * (Requirement 8.4). Throws ApiError(404) for an unknown or cross-tenant id.
   */
  update: (actionId: string, payload: ActionUpdate) =>
    api.patch<ActionItem>(`/actions/${actionId}`, payload),

  /**
   * Permanently delete an action item. Also removes any Google Calendar event
   * links for the action. Throws ApiError(404) for an unknown/cross-tenant id.
   */
  remove: (actionId: string) => api.del<void>(`/actions/${actionId}`),
};
